language: java

services:
  - docker

env:
  global:
    - BRANCH=${TRAVIS_BRANCH}
    - TAG=${TRAVIS_TAG}
    - SHA=${TRAVIS_COMMIT}
  matrix:
    - SUB_PROJECT=indexer
    - SUB_PROJECT=haystack-trace-provider

script:
  # build, create docker image
  # upload to dockerhub only for master(non PR) and tag scenario
  - if ([ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]) || [ -n "$TRAVIS_TAG" ];  then "$SUB_PROJECT"/make release; else "$SUB_PROJECT"/make all; fi
