#
#  Copyright 2019 Expedia, Inc.
#
#       Licensed under the Apache License, Version 2.0 (the "License");
#       you may not use this file except in compliance with the License.
#      You may obtain a copy of the License at
#
#           http://www.apache.org/licenses/LICENSE-2.0
#
#       Unless required by applicable law or agreed to in writing, software
#       distributed under the License is distributed on an "AS IS" BASIS,
#       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#       See the License for the specific language governing permissions and
#       limitations under the License.
#
version: "3"
services:
   mysql:
     image: mysql:8.0.13
     environment:
       MAX_HEAP_SIZE: 256m
       HEAP_NEWSIZE: 256m
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: haystack-spans
     ports:
      - "3306:3306"
     command: --default-authentication-plugin=mysql_native_password

  storage-backend:
    image: expediadotcom/haystack-trace-backend-mysql:1.0.8
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_LOG_LEVEL: "DEBUG"
      JAVA_XMS: 128m
    depends_on:
      - "mysql"
    restart: always
    # uncomment below port mapping to expose and connect to this application out of local docker container network
#    ports:
#      - "8090:8090"

  trace-reader:
    image: expediadotcom/haystack-trace-reader:1.0.8
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_PROP_BACKEND_CLIENT_HOST: "storage-backend"
      JAVA_XMS: 128m
    restart: always

  trace-indexer:
    image: expediadotcom/haystack-trace-indexer:1.0.8
    environment:
      HAYSTACK_GRAPHITE_ENABLED: "false"
      HAYSTACK_PROP_BACKEND_CLIENT_HOST: "storage-backend"
      HAYSTACK_PROP_SERVICE_METADATA_ENABLED: "true"
      HAYSTACK_PROP_KAFKA_MAX_WAKEUPS: "100"
      HAYSTACK_PROP_SERVICE_METADATA_FLUSH_INTERVAL_SEC: "0"
      JAVA_XMS: 128m
    depends_on:
      - "elasticsearch"
    restart: always

  elasticsearch:
      image: elastic/elasticsearch:6.0.1
      environment:
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        xpack.security.enabled: "false"
      ports:
        - "9200:9200"
      restart: always

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafkasvc:
    image: wurstmeister/kafka:2.11-1.1.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafkasvc:9092,OUTSIDE://localhost:19092
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "proto-spans:1:1,metricpoints:1:1,metric-data-points:1:1,mdm:1:1,metrics:1:1,graph-nodes:1:1,service-graph:1:1,mapped-metrics:1:1,anomalies:1:1,alerts:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
      - "19092:19092"


  ui:
    image: expediadotcom/haystack-ui:1.1.4
    volumes:
      - ./:/data
    ports:
      - "8080:8080"
    environment:
      HAYSTACK_OVERRIDES_CONFIG_PATH: /data/connectors.json
      HAYSTACK_PROP_CONNECTORS_TRACES_CONNECTOR__NAME: "haystack"
      HAYSTACK_PROP_CONNECTORS_TRACES_SERVICE__REFRESH__INTERVAL__IN__SECS: "0"
      HAYSTACK_PROP_CONNECTORS_TRACES_HAYSTACK__HOST: "trace-reader"
      HAYSTACK_PROP_CONNECTORS_TRACES_HAYSTACK__PORT: "8088"